package com.gabriellima.MesaFacil2026.Enums;

public enum ReservaTipoDeEvento {


    ANIVERSARIO,
    CASAMENTO,
    NOIVADO,
    ENCONTRO_ROMANTICO,
    REUNIAO_FAMILIAR,
    REUNIAO_EMPRESARIAL,
    CONFRATERNIZACAO_EMPRESA,
    ALMOCO_NEGOCIOS,
    EVENTO_NETWORKING,
    FORMATURA,
    CHA_DE_BEBE,
    CHA_DE_PANELA,
    DESPEDIDA_SOLTEIRO,
    FESTA_TEMATICA,
    RESERVA_COMUM,
    CELEBRACAO_ESPECIAL,
    JANTAR_COMEMORATIVO,
    EVENTO_PRIVADO



}
